spring:
  config:
    activate:
      on-profile: prod # production ( 실제 운영 환경 )

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://seoil-web-project00.cvkwqc0ua07p.ap-northeast-2.rds.amazonaws.com:3306/tjournal_db?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: seoil
    password: tjdlfeogkrry

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 250MB
      location: c:\\Temp\\upload

  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
      s3:
        bucket: banglog
      region:
        static: ap-southeast-2 # 리전 정보(서울)
      stack:
        auto: false

  naver:
    client:
      id: ${NAVER_CLIENT_ID}
      secret: ${NAVER_CLIENT_SECRET}
    login:
      id: ${NAVER_LOGIN_CLIENT_ID}
      secret: ${NAVER_LOGIN_CLIENT_SECRET}
    scope:
      - name
      - email
    client-name: Naver
    authorization-grant-type: authorization_code
    redirect-uri: http://localhost:8088/oauth/login

  kakao:
    login:
      rest-api: ${KAKAO_REST_API_KEY}
    redirect-uri: http://localhost:8088/oauth/login/kakao_redirect

  mail:
    host: smtp.gmail.com
    port: 587
    username: qudgns4475@gmail.com
    password: fmil pltn paop lmzb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

    mail-auth-code-expiration-millis: 1800000

# application-local.yml (or application-prod.yml)
logging:
  level:
    root: INFO
    org.springframework: WARN
    com.example.tjournal: INFO
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
